/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dbaseAccount;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class finalbooking extends javax.swing.JFrame {
ResultSet rs,rs1;
String trainno,trainname,fare,dept,date,fullname,contact;
String source,destination,acclass,arr,user,arrreturn;
int j,x;
    /**
     * Creates new form finalbooking
     */
    public finalbooking() {
        initComponents();
        setVisible(true);
             Color backgroundcolor = new Color(200,204,255);
this.getContentPane().setBackground(backgroundcolor);
combosal.removeAllItems();
combosal.addItem("Mr.");
combosal.addItem("Ms.");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combosal = new javax.swing.JComboBox<>();
        lblname = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        lblcontactno = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        lbltitle = new javax.swing.JLabel();
        paneloneway = new javax.swing.JPanel();
        lbloneway = new javax.swing.JLabel();
        lbltrainno = new javax.swing.JLabel();
        lbltrainname = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbldep = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblsetno = new javax.swing.JLabel();
        lblsetname = new javax.swing.JLabel();
        lblsetdate = new javax.swing.JLabel();
        lblsetdep = new javax.swing.JLabel();
        lblsetfare = new javax.swing.JLabel();
        panelreturn = new javax.swing.JPanel();
        lblreturn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblretno = new javax.swing.JLabel();
        lblretname = new javax.swing.JLabel();
        lblretdate = new javax.swing.JLabel();
        lblretdep = new javax.swing.JLabel();
        lblretfare = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        butpay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 60));
        setPreferredSize(new java.awt.Dimension(1060, 650));
        getContentPane().setLayout(null);

        combosal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combosal);
        combosal.setBounds(180, 110, 56, 30);

        lblname.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("NAME :");
        getContentPane().add(lblname);
        lblname.setBounds(70, 110, 80, 20);
        getContentPane().add(txtfullname);
        txtfullname.setBounds(267, 109, 181, 30);

        lblcontactno.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lblcontactno.setForeground(new java.awt.Color(255, 255, 255));
        lblcontactno.setText("CONTACT NUMBER :");
        getContentPane().add(lblcontactno);
        lblcontactno.setBounds(36, 174, 220, 21);
        getContentPane().add(txtcontact);
        txtcontact.setBounds(267, 166, 181, 30);

        lbltitle.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("CONFIRM YOUR BOOKING");
        getContentPane().add(lbltitle);
        lbltitle.setBounds(216, 21, 682, 55);

        lbloneway.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbloneway.setText("jLabel4");

        lbltrainno.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbltrainno.setText("TRAIN NUMBER :");

        lbltrainname.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbltrainname.setText("TRAIN NAME :");

        lbldate.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbldate.setText("DATE :");

        lbldep.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbldep.setText("DEPARTURE :");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel1.setText("FARE :");

        lblsetno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblsetno.setText("jLabel9");

        lblsetname.setText("jLabel2");

        lblsetdate.setText("jLabel4");

        lblsetdep.setText("jLabel10");

        lblsetfare.setText("jLabel11");

        javax.swing.GroupLayout panelonewayLayout = new javax.swing.GroupLayout(paneloneway);
        paneloneway.setLayout(panelonewayLayout);
        panelonewayLayout.setHorizontalGroup(
            panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelonewayLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltrainno)
                    .addComponent(lbltrainname)
                    .addComponent(lbldate)
                    .addComponent(lbldep)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsetfare)
                    .addComponent(lblsetdep)
                    .addComponent(lblsetdate)
                    .addComponent(lblsetname)
                    .addComponent(lblsetno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelonewayLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lbloneway, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        panelonewayLayout.setVerticalGroup(
            panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelonewayLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbloneway)
                .addGap(40, 40, 40)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrainno)
                    .addComponent(lblsetno))
                .addGap(18, 18, 18)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrainname)
                    .addComponent(lblsetname))
                .addGap(26, 26, 26)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldate)
                    .addComponent(lblsetdate))
                .addGap(26, 26, 26)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldep)
                    .addComponent(lblsetdep))
                .addGap(18, 18, 18)
                .addGroup(panelonewayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblsetfare))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(paneloneway);
        paneloneway.setBounds(66, 214, 422, 302);

        panelreturn.setPreferredSize(new java.awt.Dimension(442, 302));

        lblreturn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblreturn.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("TRAIN NUMBER :");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel5.setText("TRAIN NAME :");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel6.setText("DATE :");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel7.setText("DEPARTURE :");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel8.setText("FARE :");

        lblretno.setText("jLabel2");

        lblretname.setText("jLabel4");

        lblretdate.setText("jLabel9");

        lblretdep.setText("jLabel10");

        lblretfare.setText("jLabel11");

        javax.swing.GroupLayout panelreturnLayout = new javax.swing.GroupLayout(panelreturn);
        panelreturn.setLayout(panelreturnLayout);
        panelreturnLayout.setHorizontalGroup(
            panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturnLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelreturnLayout.createSequentialGroup()
                        .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblretfare)
                            .addComponent(lblretdep)
                            .addComponent(lblretdate)
                            .addComponent(lblretname)
                            .addComponent(lblretno)))
                    .addGroup(panelreturnLayout.createSequentialGroup()
                        .addComponent(lblreturn)
                        .addGap(6, 6, 6)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelreturnLayout.setVerticalGroup(
            panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblreturn)
                .addGap(42, 42, 42)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblretno))
                .addGap(28, 28, 28)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblretname))
                .addGap(18, 18, 18)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblretdate))
                .addGap(28, 28, 28)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblretdep))
                .addGap(18, 18, 18)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblretfare))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(panelreturn);
        panelreturn.setBounds(541, 214, 442, 302);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 530, 97, 29);

        butpay.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        butpay.setText("MAKE PAYMENT");
        butpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butpayActionPerformed(evt);
            }
        });
        getContentPane().add(butpay);
        butpay.setBounds(500, 530, 161, 29);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AGE :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 110, 60, 21);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(630, 109, 78, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/railwaybooking.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Mainscreen m=new Mainscreen();
        m.getusername(user);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void butpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butpayActionPerformed
        // TODO add your handling code here:
        
        trainno=lblsetno.getText();
        trainname=lblsetname.getText();
        date=lblsetdate.getText();
        fare=lblsetfare.getText();
        
        dept=lblsetdep.getText();
        dbaseAccount d=new dbaseAccount();
        fullname=txtfullname.getText();
        contact=txtcontact.getText();
    try {
        d.insertdata(source, destination, trainno , trainname, fare,fullname, contact,user, acclass,date, dept, arr);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(j==1)
           
    {
        trainno=lblretno.getText();
        trainname=lblretname.getText();
        date=lblretdate.getText();
        fare=lblretfare.getText();
        
        dept=lblretdep.getText();
        
        fullname=txtfullname.getText();
        contact=txtcontact.getText();
        try {
        d.insertdata(destination, source, trainno , trainname, fare,fullname, contact,user, acclass,date, dept, arrreturn);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    JOptionPane.showMessageDialog(null,"PAYMENT SUCCESSFULL");
JOptionPane.showMessageDialog(null,"TICKET CONFIRMED");
    }//GEN-LAST:event_butpayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalbooking().setVisible(true);
            }
        });
    }

    public void filllabel(String id,String ac,Date date) throws SQLException 
    {
        dbaseAccount d=new dbaseAccount();
    try {
        rs=d.finaldepart(id,ac);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
    }
        rs.beforeFirst();
while (rs.next()== true)
{
source = rs.getString("source");
destination = rs.getString("destination");
lbloneway.setText(source + " TO "+ destination);
lblsetfare.setText(rs.getString("fare"));
lblsetname.setText(rs.getString("trainname"));
acclass=(rs.getString("class"));
arr=(rs.getString("arrival"));
lblsetno.setText(id);
lblsetdep.setText(rs.getString("dept"));
DateFormat df1 = new SimpleDateFormat("dd-MM-yyyy");
lblsetdate.setText(String.valueOf(df1.format(date)));

}
    }
    
     public void filllabelret(String idret,String ac,Date date,Date dateret) throws SQLException 
     {
                 
         //======================//
         dbaseAccount d=new dbaseAccount();
   
DateFormat df1 = new SimpleDateFormat("dd-MM-yyyy");


             try {
                 //=========================//

                 rs1=d.finaldepartret(idret, ac);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(finalbooking.class.getName()).log(Level.SEVERE, null, ex);
             }
                rs1.beforeFirst();
                while (rs1.next()== true)
                {
                    lblreturn.setText(destination+ " TO "+ source);
                    lblretfare.setText(rs1.getString("fare"));
                    lblretname.setText(rs1.getString("trainname"));
                    lblretno.setText(idret);
                    lblretdep.setText(rs1.getString("dept"));
                    arrreturn=rs1.getString("arrival");
                    //DateFormat df1 = new SimpleDateFormat("dd-MM-yyyy");
                    lblretdate.setText(String.valueOf(df1.format(dateret)));
                    
                }
}

     public void retconfirm(int i)
     {
        j=i;
               if(i==1)
{
    panelreturn.setVisible(true);
}
         else 
{
     panelreturn.setVisible(false);
}

  
     }

     public void getusername(String username)
     {
         user=username;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butpay;
    private javax.swing.JComboBox<String> combosal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldep;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lbloneway;
    private javax.swing.JLabel lblretdate;
    private javax.swing.JLabel lblretdep;
    private javax.swing.JLabel lblretfare;
    private javax.swing.JLabel lblretname;
    private javax.swing.JLabel lblretno;
    private javax.swing.JLabel lblreturn;
    private javax.swing.JLabel lblsetdate;
    private javax.swing.JLabel lblsetdep;
    private javax.swing.JLabel lblsetfare;
    private javax.swing.JLabel lblsetname;
    private javax.swing.JLabel lblsetno;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltrainname;
    private javax.swing.JLabel lbltrainno;
    private javax.swing.JPanel paneloneway;
    private javax.swing.JPanel panelreturn;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtfullname;
    // End of variables declaration//GEN-END:variables
}
