/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dbaseAccount;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author acer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Color background=new Color(200,204,255);
        this.getContentPane().setBackground(background);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbluserimg = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        butlogin = new javax.swing.JButton();
        butregister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 60));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("USER LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 170, 149, 29);

        lbluserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/loginimg.png"))); // NOI18N
        getContentPane().add(lbluserimg);
        lbluserimg.setBounds(280, 110, 98, 98);

        lbluser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbluser.setText("USERNAME");
        getContentPane().add(lbluser);
        lbluser.setBounds(270, 260, 103, 22);

        lblpass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblpass.setText("PASSWORD");
        getContentPane().add(lblpass);
        lblpass.setBounds(270, 340, 106, 22);

        txtuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtuser);
        txtuser.setBounds(400, 260, 276, 30);

        txtpass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(txtpass);
        txtpass.setBounds(400, 330, 276, 28);

        butlogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        butlogin.setText("LOG IN");
        butlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butloginMouseClicked(evt);
            }
        });
        getContentPane().add(butlogin);
        butlogin.setBounds(350, 410, 95, 31);

        butregister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        butregister.setText("REGISTER");
        butregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butregisterMouseClicked(evt);
            }
        });
        butregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butregisterActionPerformed(evt);
            }
        });
        getContentPane().add(butregister);
        butregister.setBounds(520, 410, 125, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/loginback3.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butregisterActionPerformed

    private void butregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butregisterMouseClicked
        // TODO add your handling code here:
        register r=new register();
        this.dispose();
    }//GEN-LAST:event_butregisterMouseClicked

    private void butloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butloginMouseClicked
        // TODO add your handling code here:
        String Username=txtuser.getText();
        String password=txtpass.getText();
      boolean result=false;
        
        dbaseAccount d=new dbaseAccount();
        try {
            result=d.login(Username, password);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(result){
            this.dispose();}
       
    }//GEN-LAST:event_butloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butlogin;
    private javax.swing.JButton butregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluserimg;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
