/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dbaseAccount;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class RailwayBooking extends javax.swing.JFrame {
ResultSet rs,rs1,rs2;
Date date,dateret;
String user;
    /**
     * Creates new form RailwayBooking
     */
    public RailwayBooking() throws SQLException {
        initComponents();
        setVisible(true);
        datedor.setEnabled(false);
        butgrp.add(checkone);
        butgrp.add(checkreturn);
       Date d=new Date();
       datedoj.setDate(d);
       datedor.setDate(d);
       datedoj.setMinSelectableDate(d);
       datedor.setMinSelectableDate(d);
       int mon=d.getMonth();
       int year=d.getYear();
       Date d1=new Date();
           
       if(mon>8){
         
       mon=(mon+4)%12;
       year=year+1;
       d1.setMonth(mon);
       d1.setYear(year);
       }
       else
       {
           mon=mon+4;
       }
      
       datedoj.setMaxSelectableDate(d1);
       datedor.setMaxSelectableDate(d1);
       
       fillcombobox();
     
       }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butgrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        combofrom = new javax.swing.JComboBox<>();
        lblfrom = new javax.swing.JLabel();
        lblto = new javax.swing.JLabel();
        comboto = new javax.swing.JComboBox<>();
        datedoj = new com.toedter.calendar.JDateChooser();
        comboclass = new javax.swing.JComboBox<>();
        lblclass = new javax.swing.JLabel();
        checkreturn = new javax.swing.JCheckBox();
        checkone = new javax.swing.JCheckBox();
        datedor = new com.toedter.calendar.JDateChooser();
        buttonfind = new javax.swing.JButton();
        lbldoj = new javax.swing.JLabel();
        lbldor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblindrail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 60));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbltitle.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        lbltitle.setText("B O O K");

        lbltitle1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 22)); // NOI18N
        lbltitle1.setText("YOUR TICKET");

        combofrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblfrom.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        lblfrom.setText("From");

        lblto.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblto.setText("To");

        comboto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        datedoj.setMaxSelectableDate(new java.util.Date(253370748705000L));

        comboclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblclass.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lblclass.setText("CLASS");

        checkreturn.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        checkreturn.setText("Return");
        checkreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkreturnActionPerformed(evt);
            }
        });

        checkone.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        checkone.setText("One Way");
        checkone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoneActionPerformed(evt);
            }
        });

        buttonfind.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        buttonfind.setText("Find Trains");
        buttonfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonfindActionPerformed(evt);
            }
        });

        lbldoj.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbldoj.setText("DOJ");

        lbldor.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        lbldor.setText("DOR");

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lbltitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbltitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblto)
                                    .addComponent(lblfrom))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combofrom, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE)
                                    .addComponent(comboto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbldoj)
                                .addGap(18, 18, 18)
                                .addComponent(datedoj, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblclass)
                                .addGap(18, 18, 18)
                                .addComponent(comboclass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkone)
                                .addGap(36, 36, 36)
                                .addComponent(checkreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonfind, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbldor)
                                    .addGap(18, 18, 18)
                                    .addComponent(datedor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combofrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfrom))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblto)
                    .addComponent(comboto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldoj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblclass)
                            .addComponent(comboclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datedoj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkone)
                    .addComponent(checkreturn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonfind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 333, 520);

        lblindrail.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblindrail.setForeground(new java.awt.Color(255, 255, 255));
        lblindrail.setText("INDIAN RAILWAYS");
        getContentPane().add(lblindrail);
        lblindrail.setBounds(533, 198, 401, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/railwaybooking.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkreturnActionPerformed
        // TODO add your handling code here:
        if(checkreturn.isSelected())
        {
            datedor.setEnabled(true);
        }
   
         
    }//GEN-LAST:event_checkreturnActionPerformed

    private void checkoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoneActionPerformed
        // TODO add your handling code here:
        if(checkone.isSelected())
        {
            datedor.setEnabled(false);
        }
   
    }//GEN-LAST:event_checkoneActionPerformed

    private void buttonfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonfindActionPerformed
        // TODO add your handling code here:
         String source,destination,acclass;
         
         source=combofrom.getSelectedItem().toString();
        destination=comboto.getSelectedItem().toString();
        acclass=comboclass.getSelectedItem().toString();
        date=datedoj.getDate();
        dateret=datedor.getDate();
        if(source.equals(destination))
        {
            JOptionPane.showMessageDialog(null, "ENTER VALID DETAILS");
        }
        else if(checkone.isSelected()==false && checkreturn.isSelected()==false)
       {
            JOptionPane.showMessageDialog(null, "ENTER VALID DETAILS");
       }
        else {
        train t=new train();
        t.getusername(user);
        ResultSet rs1 = null,rs2=null;
      
          dbaseAccount d=new dbaseAccount();
        if(checkreturn.isSelected())
        {     
    try {
        rs1=d.getoneway(source, destination,acclass);
        rs2=d.getreturn(source, destination, acclass);
    } catch (SQLException ex) {
        Logger.getLogger(RailwayBooking.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
       
        t.filltablereturn(rs1,rs2);
         t.jpanel(1);
    } catch (SQLException ex) {
        Logger.getLogger(RailwayBooking.class.getName()).log(Level.SEVERE, null, ex);
    }
    
            t.setclass(acclass,date);
            t.setclassret(acclass, dateret);
            //t.jpanel(1);
            
            
        }
        else if(checkone.isSelected())
        {
           // t.jpanel(0);
                 t.setclass(acclass,date);
    try {
        rs2=d.getoneway(source, destination,acclass);
    } catch (SQLException ex) {
        Logger.getLogger(RailwayBooking.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        t.filltableone(rs2);
          t.jpanel(0);
    } catch (SQLException ex) {
        Logger.getLogger(RailwayBooking.class.getName()).log(Level.SEVERE, null, ex);
    }
        }
     
        this.dispose();
       
       }
  
    }//GEN-LAST:event_buttonfindActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Mainscreen m=new Mainscreen();
        m.getusername(user);
        this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RailwayBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RailwayBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RailwayBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RailwayBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               try {
                    new RailwayBooking().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RailwayBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup butgrp;
    private javax.swing.JButton buttonfind;
    private javax.swing.JCheckBox checkone;
    private javax.swing.JCheckBox checkreturn;
    private javax.swing.JComboBox<String> comboclass;
    private javax.swing.JComboBox<String> combofrom;
    private javax.swing.JComboBox<String> comboto;
    private com.toedter.calendar.JDateChooser datedoj;
    private com.toedter.calendar.JDateChooser datedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblclass;
    private javax.swing.JLabel lbldoj;
    private javax.swing.JLabel lbldor;
    private javax.swing.JLabel lblfrom;
    private javax.swing.JLabel lblindrail;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lblto;
    // End of variables declaration//GEN-END:variables
 private void fillcombobox() throws SQLException {
        combofrom.removeAllItems();
        comboto.removeAllItems();
        comboclass.removeAllItems();
        dbaseAccount d=new dbaseAccount();
         rs=d.getSourceCity();
         while(rs.next()==true)
         {
             combofrom.addItem(rs.getString("source"));
         }
         rs1=d.getDestinationCity();
          while(rs1.next()==true)
         {
             comboto.addItem(rs1.getString("destination"));
         }
          rs2=d.getclass();
           while(rs2.next()==true)
         {
             comboclass.addItem(rs2.getString("class"));
         }
    }
 
 public void getusername(String username)
 {
     user=username;
 }
}






