/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dbaseAccount;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        lblpass = new javax.swing.JLabel();
        buttonreg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 60));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        lbltitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbltitle.setText("PLEASE REGISTER YOURSELF!");
        getContentPane().add(lbltitle);
        lbltitle.setBounds(344, 81, 369, 29);

        lbluser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbluser.setText("SET USERNAME");
        getContentPane().add(lbluser);
        lbluser.setBounds(315, 176, 143, 26);

        txtuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtuser.setToolTipText("");
        txtuser.setMinimumSize(new java.awt.Dimension(6, 28));
        getContentPane().add(txtuser);
        txtuser.setBounds(502, 178, 210, 30);

        txtpass.setMinimumSize(new java.awt.Dimension(6, 28));
        getContentPane().add(txtpass);
        txtpass.setBounds(502, 235, 210, 30);

        lblpass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblpass.setText("SET PASSWORD");
        getContentPane().add(lblpass);
        lblpass.setBounds(310, 240, 160, 20);

        buttonreg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonreg.setText("REGISTER!");
        buttonreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonregMouseClicked(evt);
            }
        });
        getContentPane().add(buttonreg);
        buttonreg.setBounds(570, 320, 129, 31);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 320, 120, 30);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/loginback3.png"))); // NOI18N
        lblbackground.setText("jLabel1");
        getContentPane().add(lblbackground);
        lblbackground.setBounds(0, 0, 1050, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonregMouseClicked
        // TODO add your handling code here
        String Username=txtuser.getText();
        String password=txtpass.getText();
        if(Username.equals(""))
                
        {
            JOptionPane.showMessageDialog(this, "ENTER VALID CREDENTIALS");
            
        }
        else{
        dbaseAccount d=new dbaseAccount();
        try {
            d.register(Username, password);
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_buttonregMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
        Login L=new Login();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonreg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
