/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dbaseAccount;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author acer
 */
public class train extends javax.swing.JFrame {
String ac,acret,user;
Date d,dret;
int j;
    /**
     * Creates new form train
     */
    public train() {
        initComponents();
        setVisible(true);
        Color backgroundcolor = new Color(200,204,255);
this.getContentPane().setBackground(backgroundcolor);
 
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableoneway = new javax.swing.JTable();
        lbloneway = new javax.swing.JLabel();
        combooneway = new javax.swing.JComboBox<>();
        lblselectoneway = new javax.swing.JLabel();
        panelreturn = new javax.swing.JPanel();
        lblreturn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablereturn = new javax.swing.JTable();
        lblselectreturn = new javax.swing.JLabel();
        comboreturn = new javax.swing.JComboBox<>();
        buttonproceed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 60));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        tableoneway.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableoneway.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tableoneway);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 65, 1020, 101);

        lbloneway.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lbloneway.setForeground(new java.awt.Color(255, 255, 255));
        lbloneway.setText("ONE WAY");
        getContentPane().add(lbloneway);
        lbloneway.setBounds(62, 26, 130, 21);

        combooneway.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combooneway);
        combooneway.setBounds(564, 195, 118, 20);

        lblselectoneway.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lblselectoneway.setForeground(new java.awt.Color(255, 255, 255));
        lblselectoneway.setText("SELECT YOUR TRAIN");
        getContentPane().add(lblselectoneway);
        lblselectoneway.setBounds(305, 193, 230, 21);

        lblreturn.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        lblreturn.setText("RETURN");

        tablereturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablereturn);

        lblselectreturn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        lblselectreturn.setText("SELECT YOUR TRAIN");

        comboreturn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelreturnLayout = new javax.swing.GroupLayout(panelreturn);
        panelreturn.setLayout(panelreturnLayout);
        panelreturnLayout.setHorizontalGroup(
            panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturnLayout.createSequentialGroup()
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelreturnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(panelreturnLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblreturn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelreturnLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lblselectreturn)
                .addGap(62, 62, 62)
                .addComponent(comboreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelreturnLayout.setVerticalGroup(
            panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblreturn)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(panelreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblselectreturn)
                    .addComponent(comboreturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelreturn);
        panelreturn.setBounds(10, 270, 1020, 287);

        buttonproceed.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        buttonproceed.setText("Proceed");
        buttonproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonproceedActionPerformed(evt);
            }
        });
        getContentPane().add(buttonproceed);
        buttonproceed.setBounds(866, 189, 119, 29);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(744, 189, 87, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/travel/railwaybooking.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonproceedActionPerformed
        // TODO add your handling code here:
        finalbooking f=new finalbooking();
        f.getusername(user);
        String id=combooneway.getSelectedItem().toString();
        //String idret=comboreturn.getSelectedItem().toString();
         
        try {
            if(j==1)
            {
                String idret=comboreturn.getSelectedItem().toString();
                f.filllabel(id,ac,d);
                f.filllabelret(idret, ac, d,dret);
                f.retconfirm(1);
               
            }
            else
            {
            f.filllabel(id,ac,d);
            f.retconfirm(0);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(train.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_buttonproceedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // TODO add your handling code here:
        RailwayBooking r=new RailwayBooking();
        r.getusername(user);
    } catch (SQLException ex) {
        Logger.getLogger(train.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new train().setVisible(true);
            }
        });
    }
    
    public void filltableone(ResultSet rs) throws SQLException
    {
       
        TableModel tmodel = new DefaultTableModel();
        tableoneway.setModel(DbUtils.resultSetToTableModel(rs));
         combooneway.removeAllItems();
       comboreturn.removeAllItems();
       rs.beforeFirst();
       while(rs.next()==true)
       {
           combooneway.addItem(rs.getString("trainno"));
       }
    }
    
    public void filltablereturn(ResultSet rs1,ResultSet rs2) throws SQLException
    {
        TableModel tmodel = new DefaultTableModel();
        tableoneway.setModel(DbUtils.resultSetToTableModel(rs1));
         combooneway.removeAllItems();
       comboreturn.removeAllItems();
       rs1.beforeFirst();
       while(rs1.next()==true)
       {
           combooneway.addItem(rs1.getString("trainno"));
       }
    
    
    //TableModel tmodel = new DefaultTableModel();
        tablereturn.setModel(DbUtils.resultSetToTableModel(rs2));
        
       rs2.beforeFirst();
       while(rs2.next()==true)
       {
           comboreturn.addItem(rs2.getString("trainno"));
       }
    }
       
    public void setclass(String acclass,Date date)
    {
        ac=acclass;
        d=date;
    }
    
    public void setclassret(String acclass,Date date)
    {
        acret=acclass;
        dret=date;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonproceed;
    private javax.swing.JComboBox<String> combooneway;
    private javax.swing.JComboBox<String> comboreturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbloneway;
    private javax.swing.JLabel lblreturn;
    private javax.swing.JLabel lblselectoneway;
    private javax.swing.JLabel lblselectreturn;
    private javax.swing.JPanel panelreturn;
    private javax.swing.JTable tableoneway;
    private javax.swing.JTable tablereturn;
    // End of variables declaration//GEN-END:variables

    public void jpanel(int i) {
        j=i;
        if(i==1)
        {
            panelreturn.setVisible(true);
            
        }
        else
        {
            panelreturn.setVisible(false);
            lblreturn.setVisible(false);
        }
    }

   public void getusername(String username)
   {
       user=username;
   }
}
